C_NETWORK_CONNECT=1
C_CREATE_USER=2
C_DISCONNECT=3
C_USER_ADD_CHAR=4
C_USER_DELETE_CHAR=5
C_NETWORK_USER_CHOOSE_HERO=6
C_NETWORK_USER_CHANGE_ZONE=7
C_NETWORK_INFO_ZONE=8


C_NETWORK_CHARACTER_KEYBOARD=109
C_NETWORK_CHARACTER_UPDATE_POS=110
C_NETWORK_NPC_INCOMING=111
C_NETWORK_NPC_UPDATE_POS=112
C_NETWORK_CHAR_SHOT=113
C_NETWORK_NEW_SHOT=114
C_NETWORK_REMOVE_SHOT=115
C_NETWORK_COLLIDE_SHOT=116
C_NETWORK_EXPLOSION=117
C_NETWORK_TAKE_DAMAGE_NPC=118
C_NETWORK_REMOVE_NPC=119