C_DIALOG_TYPE_DIALOGUE=1
C_DIALOG_TYPE_RUMOR=2
C_DIALOG_TYPE_MISSION=3

############TYPE OBJECTIF##############
C_OBJECTIF_TRANSPORT=1
C_OBJECTIF_DESTROY=2

############STATUS MISSION############
C_STATEMISSION_DONTHAVE=0
C_STATEMISSION_INPROGRESS=1
C_STATEMISSION_FINISHED=2
C_STATEMISSION_SUCCESS=3
############REWARD###################"
C_REWARD_COIN=1